GET http://localhost:3001/api/info/1

###

GET http://localhost:3001/api/persons

###

DELETE  http://localhost:3001/api/info/1

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"Greg Foulkes",
    "number":"079-679-4078"
}
